// gen-fonts.mjs — fetch the exact Google Fonts used by the decks and write a
// fully self-contained fonts.css with base64-inlined woff2 (no network at view
// time). Kept to latin + latin-ext subsets to keep the file reasonable.
//
// Run once (needs network):  node gen-fonts.mjs
import { writeFile } from 'node:fs/promises'

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,400;0,500;0,600;0,700;1,400;1,600&family=JetBrains+Mono:wght@400;500&display=swap'
const KEEP_SUBSETS = new Set(['latin', 'latin-ext'])
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36'

const HEADER = `/*
 * Self-contained fonts (base64-inlined woff2) — generated by gen-fonts.mjs.
 * Committed on purpose so builds need no network; regenerate: node gen-fonts.mjs
 *
 * Embedded typefaces:
 *   Inter — Copyright The Inter Project Authors (https://github.com/rsms/inter)
 *   JetBrains Mono — Copyright 2020 The JetBrains Mono Project Authors
 *     (https://github.com/JetBrains/JetBrainsMono)
 * Both are licensed under the SIL Open Font License 1.1
 * (https://openfontlicense.org).
 */
`

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()

// Google's CSS is a sequence of:  /* subset */\n @font-face { ... }
const blocks = css.split('/*').slice(1) // each starts with " subset */ @font-face..."
let out = HEADER
let inlined = 0

for (const b of blocks) {
  const subset = b.slice(0, b.indexOf('*/')).trim()
  if (!KEEP_SUBSETS.has(subset)) continue
  const face = '@font-face' + b.slice(b.indexOf('@font-face') + '@font-face'.length)
  const m = face.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/)
  if (!m) continue
  const buf = Buffer.from(
    await (await fetch(m[1], { headers: { 'User-Agent': UA } })).arrayBuffer(),
  )
  const dataUri = `url(data:font/woff2;base64,${buf.toString('base64')}) format('woff2')`
  out +=
    '/* ' + subset + ' */\n' + face.replace(/url\([^)]+\)\s*format\([^)]+\)/, dataUri).trim() + '\n'
  inlined++
}

await writeFile('fonts.css', out)
console.log(
  `fonts.css written — ${inlined} faces inlined, ${(out.length / 1024 / 1024).toFixed(2)} MB`,
)
